### PR TITLE
Remove dependency of uuid, add an option

### LINKED ISSUE #92: remove uuid dependency
it looks that mixerclient added a dependency on libuuid from
e2fsprogs, which isn't part of base OS (i.e. Goobuntu doesn't have it
installed by default).

However, this dependency wasn't added via Bazel, so the build is
broken and not hermetic at all.

I wanted to make a PR adding libuuid, but it looks that it's licensed
under GPLv2, which means that we cannot statically link against it,
AFAIK.

I think it is from util-linux, yes it is still LGPL, so I think we should remove the dependency.

Envoy has its own uuid impl:
https://github.com/lyft/envoy/blob/master/source/common/runtime/runtime_impl.cc#L28

### PR DESCRIPTION
**Pull request by lizan**
Fixes #92

### CODE REVIEW

File: src/client_impl.cc [hunk 1]
```diff
@@ -53,7 +35,9 @@ MixerClientImpl::MixerClientImpl(const MixerClientOptions &options)
   quota_cache_ =
       std::unique_ptr<QuotaCache>(new QuotaCache(options.quota_options));
 
-  deduplication_id_base_ = GenerateUUID();
+  if (options_.uuid_generate_func) {
```
Comment (qiwzhang) [inline src/client_impl.cc]: we should provide a default uuid function.

For Linux,  we can just try to read "/proc/" as Envoy.

Comment (lizan) [inline src/client_impl.cc]: That was my initial thought, but wouldn't it add a blocking read?

Comment (qiwzhang) [inline src/client_impl.cc]: it is only called once at constructor.  so a blocking read at init() is fine.

**Comment by PiotrSikora** [comment]
I'll add custom implementation once I'm done optimizing it (see: https://github.com/lyft/envoy/pull/1401).

**Comment by lizan** [comment]
@PiotrSikora The idea is use that as a part of Options.

**Comment by PiotrSikora** [comment]
@lizan ah, I see.

**Comment by qiwzhang** [comment]
may not need to be so complicated.  not need to add a function in option.  Just in the constructor,  if we can read "/proc", just use it.  otherwise, "base" can be empty string.

File: src/client_impl.cc (hunk 1 above)
Comment (lizan) [inline src/client_impl.cc]: Adding that would essentially same as copying https://github.com/lyft/envoy/blob/master/source/common/runtime/runtime_impl.cc#L26 to here, because we need hex convert etc. I don't think it should be. We can make this option mandatory, so a constructor crash here.
